feat(09-functions): add wf file

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,23 +1,25 @@
 name: 09 - Using Functions
 on:
-    push: 
-    workflow_dispatch: 
+  push:
+  workflow_dispatch:
 
 jobs:
-    echo1:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Failing step
-              run: exit 1
-            - name: I will be skipped
-              if: success()
-              run: echo "I will print if previous steps succeed."
-            - name: I will execute
-              if: failure()
-              run: echo "I will print if any previous step fails."
-            - name: I will execute
-              if: ${{ !cancelled() }}
-              run: echo "I will always print, except when the workflow is cancelled."
-            - name: I will execute when cancelled
-              if: cancelled()
-              run: echo "I will always print when the workflow is cancelled."
+  echo1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Sleep for 20 seconds
+        run: sleep 20
+      - name: Failing step
+        run: exit 1
+      - name: I will be skipped
+        if: success()
+        run: echo "I will print if previous steps succeed."
+      - name: I will execute
+        if: failure()
+        run: echo "I will print if any previous step fails."
+      - name: I will execute
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+      - name: I will execute when cancelled
+        if: cancelled()
+        run: echo "I will always print when the workflow is cancelled."
